### ISSUE TITLE
Is anyone still interested in keeping the website alive? 

### ISSUE THREAD

**Issue by arthurmathies** [hacksquare/Challengr#132]
The Namecheap domain challengr.io is expiring in about 4 weeks. Anyone very much interested in keeping it? If not I would shut it down.

**Comment by grooveIsAll** [comment]
Honestly haven't challenged anyone since December of 2015.  I believe I
challenged Kev Kev to have something other than a burrito from Ay Caramba
for lunch.  The charity still hasn't received its $.50 pledge. ::teardrop::
 If no one else objects, I would say go ahead and pull the plug. Hope you
are all well. Thanks Arthur!

Cheers,

-Bobby

spankStack.pop('Arthur');

**Comment by arthurmathies** [comment]
As of today the plug is officially pulled. No more challengr.io :cry:

spankStack.push('Bobby')
@grooveIsAll: in ES6 you don't need those semicolons Bobby :laughing:

But since there can be good reasons for semicolons in JS I will pop you right back off.
spankStack.pop('Bobby')
